---
name: Semgrep Differential Scan
on:
  pull_request

jobs:

  semgrep-diff:
    runs-on: ubuntu-latest

    steps:
      - name: clone application source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: 'src'

      - name: scan source code
        uses: docker://returntocorp/semgrep
        run: semgrep scan --error --metrics=off --baseline-commit ${{ github.event.pull_request.base.sha }} --config="p/default"
        working-directory: src